# Generated by Django 3.0.8 on 2020-07-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'socials',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('social_account', models.CharField(max_length=100)),
                ('social', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Social')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
