# Generated by Django 3.1 on 2020-08-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20200804_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordaccount',
            name='is_created',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='wordaccount',
            name='is_updated',
            field=models.BooleanField(default=0),
        ),
    ]
